#!/usr/bin/env python2

import zipfile
import xml.dom.minidom
from pylib.xmlutil import getText, getInput

mydoc = zipfile.ZipFile(getInput())
document = mydoc.read('word/document.xml')
dom = xml.dom.minidom.parseString(document)
print(getText(dom))
