#!/usr/bin/env python

import csv
import difflib
import gzip
import sys


def opencsv(fn):
    if fn.endswith('.gz'):
        f = gzip.open(fn, 'r')
    else:
        f = open(fn, 'r')
    return csv.DictReader(f)


c1, c2 = map(opencsv, sys.argv[1:3])

RETVAL = 0

f1 = sorted(c1.fieldnames)
f2 = sorted(c2.fieldnames)
if f1 != f2:
    RETVAL = 1
    print 'FIELDNAMES DIFFER'
    print '\n'.join(difflib.unified_diff(sorted(f1), sorted(f2)))

common_f = set(f1).intersection(f2)
key_f = lambda x: tuple(x[f] for f in sorted(common_f))
d1 = sorted(c1, key=key_f)
d2 = sorted(c2, key=key_f)
if d1 != d2:
    RETVAL = 1
    d1_ = [dict(item for item in row.items() if item[0] in common_f)
           for row in d1]
    d2_ = [dict(item for item in row.items() if item[0] in common_f)
           for row in d2]
    if d1_ != d2_:
        print 'VALUES DIFFER'
        s1 = []
        for item in d1_:
            s1.extend(str(item) for item in sorted(item.iteritems()))
        s2 = []
        for item in d2_:
            s2.extend(str(item) for item in sorted(item.iteritems()))
        print '\n'.join(difflib.unified_diff(s1, s2))

sys.exit(RETVAL)
