#!/usr/bin/env python

import csv
import sys


data = csv.DictReader(sys.stdin)
cols = sys.argv[1:] if len(sys.argv) > 1 else data.fieldnames

for col in cols:
    print '%10s\t' % col,
print
for row in data:
    for col in cols:
        print '%10s\t' % row[col],
    print
